CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Email" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "DueDate" timestamp with time zone,
    "EstimatedHours" numeric(10,2),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ProjectId" integer NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "AssignedToUserId" integer,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TaskItems_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TaskItems_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TaskItemId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Message" character varying(500) NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    "TaskItemId" integer,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActionType" integer NOT NULL,
    "OldValue" character varying(500),
    "NewValue" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "TaskItemId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TaskHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskHistories_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Projects" ("Id", "CreatedAt", "Description", "IsActive", "Name")
VALUES (1, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Proyecto de ejemplo', TRUE, 'Proyecto Demo');
INSERT INTO "Projects" ("Id", "CreatedAt", "Description", "IsActive", "Name")
VALUES (2, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Proyecto importante', TRUE, 'Proyecto Alpha');
INSERT INTO "Projects" ("Id", "CreatedAt", "Description", "IsActive", "Name")
VALUES (3, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Proyecto secundario', TRUE, 'Proyecto Beta');

CREATE INDEX "IX_Comments_TaskItemId" ON "Comments" ("TaskItemId");

CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

CREATE INDEX "IX_Notifications_TaskItemId" ON "Notifications" ("TaskItemId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_TaskHistories_TaskItemId" ON "TaskHistories" ("TaskItemId");

CREATE INDEX "IX_TaskHistories_UserId" ON "TaskHistories" ("UserId");

CREATE INDEX "IX_TaskItems_AssignedToUserId" ON "TaskItems" ("AssignedToUserId");

CREATE INDEX "IX_TaskItems_CreatedByUserId" ON "TaskItems" ("CreatedByUserId");

CREATE INDEX "IX_TaskItems_ProjectId" ON "TaskItems" ("ProjectId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

SELECT setval(
    pg_get_serial_sequence('"Projects"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Projects") + 1,
        nextval(pg_get_serial_sequence('"Projects"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124050752_InitialCreate', '10.0.2');

COMMIT;

